version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: employee
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-net

  springboot-app:
    container_name: spring-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/employee?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
